import { useRef, useState } from "react";
import "./App.css";
import PromptInput from "./components/PromptInput.jsx";
import LoadingState from "./components/LoadingState.jsx";
import ErrorState from "./components/ErrorState.jsx";
import EmptyState from "./components/EmptyState.jsx";
import ModeToggle from "./components/ModeToggle.jsx";
import FlashcardDeck from "./components/FlashcardDeck.jsx";
import Quiz from "./components/Quiz.jsx";
import { generateStudySet, ApiError } from "./lib/api.js";
import { validateResult } from "./lib/validateResult.js";

// 'idle' -> nothing generated yet
// 'loading' -> a request is in flight
// 'error' -> the last request failed (network, timeout, bad shape, ...)
// 'success' -> `studySet` holds a validated { topic, cards }
export default function App() {
  const [status, setStatus] = useState("idle");
  const [studySet, setStudySet] = useState(null);
  const [error, setError] = useState(null);
  const [mode, setMode] = useState("flashcards");
  const [lastInput, setLastInput] = useState("");

  // Guards against a slow, older request resolving after a faster, newer
  // one and silently clobbering the correct result. Every call to
  // runGeneration bumps this counter and captures its own id; when a
  // response comes back, it's only applied if the id it captured is still
  // the current one.
  const requestId = useRef(0);
  const abortRef = useRef(null);

  async function runGeneration(topic) {
    // Cancel whatever request is currently in flight, if any — no point
    // letting an abandoned request keep running.
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    const id = ++requestId.current;
    setLastInput(topic);
    setStatus("loading");
    setError(null);

    try {
      const raw = await generateStudySet(topic, { signal: controller.signal });
      if (id !== requestId.current) return; // a newer request has since started

      const result = validateResult(raw);
      if (!result.valid) {
        setStatus("error");
        setError({ code: "BAD_SHAPE", message: result.reason });
        return;
      }

      setStudySet(result.data);
      setMode("flashcards");
      setStatus("success");
    } catch (err) {
      if (id !== requestId.current) return; // a newer request has since started
      const apiErr = err instanceof ApiError ? err : new ApiError("UNKNOWN", err?.message);
      setStatus("error");
      setError({ code: apiErr.code, message: apiErr.message });
    }
  }

  function handleRetry() {
    if (lastInput) runGeneration(lastInput);
  }

  return (
    <div className="page">
      <header className="page-header">
        <h1>Study Deck</h1>
        <p>
          Paste notes or a topic and get an interactive flashcard deck and quiz —
          generated by an LLM, rendered as real components, never a chat log.
        </p>
      </header>

      <PromptInput onSubmit={runGeneration} isLoading={status === "loading"} />

      {status === "loading" && <LoadingState />}
      {status === "error" && <ErrorState error={error} onRetry={handleRetry} />}
      {status === "idle" && <EmptyState />}

      {status === "success" && studySet && (
        <section>
          <div className="toolbar">
            <h2 className="set-title">{studySet.topic}</h2>
            <ModeToggle mode={mode} onChange={setMode} />
          </div>
          {mode === "flashcards" ? (
            <FlashcardDeck cards={studySet.cards} />
          ) : (
            <Quiz cards={studySet.cards} />
          )}
        </section>
      )}
    </div>
  );
}
